fix last change

diff --git a/backup_git b/backup_git
--- a/backup_git
+++ b/backup_git
@@ -20,7 +20,7 @@ done
 # where backups are stored
 BACKUP_HOME=/Volumes/Elvis/backups
 
-cd $BACKUP_HOME || echo "Cannot cd to ${BACKUP_HOME} so  exiting" && exit 1
+cd $BACKUP_HOME || ( echo "Cannot cd to ${BACKUP_HOME} so  exiting" && exit 1 )
 
 # list of repos to backup
 REPO_NAMES=( \
@@ -42,6 +42,7 @@ for repoName in "${REPO_NAMES[@]}"
 do
 	repos=${BACKUP_HOME}/$repoName
 	echo $repos
+	cd $repos
 	git remote update
 
 	if [ -z "$GC" ]
