slightly better error handling

diff --git a/cp_genesis_ubuntu b/cp_genesis_ubuntu
--- a/cp_genesis_ubuntu
+++ b/cp_genesis_ubuntu
@@ -1,8 +1,15 @@
 #!/usr/bin/env bash
 #
 MACHINE=Genesis
-SOURCE=/media/asherman/$MACHINE/from_elvis/Elvis/itunes/Music
-MOVIES=/media/asherman/$MACHINE/from_elvis/Elvis/dvd/Movies
+MOUNT=/media/asherman/$MACHINE
+
+if [ ! -d  "$MOUNT" ]; then
+  echo "could not find $MOUNT"
+  exit 1
+fi
+
+SOURCE=$MOUNT/from_elvis/Elvis/itunes/Music
+MOVIES=$MOUNT/from_elvis/Elvis/dvd/Movies
 
 echo "copying music"
 rsync -av --delete --ignore-errors  ${SOURCE} /Andrew
